update: upgrade to Angular 15
mattlewis92/angularx-flatpickr pull request #53
Opened 2024-07-19 10:36 UTC by aparzi

The library now supports angular 15.

2024-07-19 18:10 UTC, mattlewis92 requested changes
Lookin good, thanks! Just had a few minor things. Also you said on your email that you wanted to upgrade to a higher angular version than v15, do you want to do that on this PR as well?

2024-07-19 18:10 UTC, mattlewis92 commented on package.json
> +  "version": "8.0.0",
Please can you revert this, as it will be bumped automatically on release

2024-07-19 18:10 UTC, mattlewis92 commented on package.json
>    "description": "An angular 14.0+ wrapper for flatpickr",
Can you find and replace all references to `angular 14` -> `angular 15` in the repo?

2024-07-19 18:10 UTC, mattlewis92 commented on package.json
> -    "@angular/core": ">=5.0.0",
Please re-add these peer dependencies and set them to `>=15.0.0` as they can be quick helpful to users

2024-07-19 19:58 UTC, aparzi commented
> Looking good, thanks! Just had a few minor things. Also you said on your email that you wanted to upgrade to a higher angular version than v15, do you want to do that on this PR as well?

Hi @mattlewis92,
yes of course but I wanted to do more releases so as to support all versions, not make the direct jump from 14 to 18. Release all versions up to 18 and from 17 also have SSR management?

2024-07-20 09:39 UTC, aparzi commented
Hi @mattlewis92,
I have update this PR. Can you check please?

2024-07-25 11:00 UTC, mattlewis92 approved these changes
LGTM! I'm putting this in to a `next` branch for now and then we can release all the major version bumps in a single release

2024-07-25 11:01 UTC, merged